#!/bin/bash

# import parameters
. /etc/parallelcluster/cfnconfig
export USERNAME=pcluster
export NEWUID=2000
export SSHKEY=("")
export HOMEDIR=/shared/home/${USERNAME}

if [ ! -e "/shared/home" ]; then
  mkdir -p /shared/home
fi

#useradd -m -b /shared/home -u ${NEWUID} -U ${USERNAME}
# encrypted password is generated by "openssl passwd -1"
useradd -m -b /shared/home -u ${NEWUID} -U ${USERNAME} -p '$1$BtdUTyMN$Web3zFBVDo5i5Zsap34KK0'

if [[ ! -d ${HOMEDIR}/.ssh ]]
then
  mkdir ${HOMEDIR}/.ssh
fi

for key in "${SSHKEY[@]}"; do
  if ! grep -q "${key}" ${HOMEDIR}/.ssh/authorized_keys
  then
    echo "${key}" >> ${HOMEDIR}/.ssh/authorized_keys
  fi
done

# Generate SSH key for in-cluster use
if [[ ! -f ${HOMEDIR}/.ssh/id_rsa ]]
then
  echo "Generating key for ${USERNAME}"
  ssh-keygen -f ${HOMEDIR}/.ssh/id_rsa -N ""
  cat ${HOMEDIR}/.ssh/id_rsa.pub >> ${HOMEDIR}/.ssh/authorized_keys
fi

# if this user is admin
usermod -a -G admin ${USERNAME}

chown -R ${USERNAME}:${USERNAME} ${HOMEDIR}
chmod 700 ${HOMEDIR}/.ssh
chmod 600 ${HOMEDIR}/.ssh/authorized_keys
